name: CLA

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.BOT }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.BOT }}
        with:
          path-to-signatures: 'signatures-v2.json'
          path-to-document: 'https://github.com/LightHostingFree/free-domain/blob/main/terms.md'
          branch: 'main'
          allowlist: lhfd-bot,bot*
          remote-organization-name: 'Light-Hosting'
          remote-repository-name: 'cla'
